### PR TITLE
overview UI and implementation of account mixer

### PR DESCRIPTION
**Pull request by macsleven**
Screenshot 2020-12-30 at 16 36 17 Screenshot 2021-02-04 at 23 57 52 Screenshot 2021-02-05 at 00 26 36
Screenshot 2021-02-05 at 00 11 45

Screenshot 2020-12-30 at 16 37 46 Screenshot 2020-12-30 at 17 05 47 Screenshot 2020-12-30 at 17 12 39
Screenshot 2020-12-30 at 21 39 32
 Screenshot 2020-12-31 at 08 02 07 Screenshot 2020-12-31 at 08 03 25

### CODE REVIEW

**Review by dreacot — CHANGES_REQUESTED** [review]
While trying the send to account, the unmixed account doesn't show
Screenshot from 2021-05-12 02-17-40

**Comment by dreacot** [comment]
I get a yellow icon for transfers, it should be gray

Screenshot from 2021-05-12 02-24-46

**Comment by dreacot** [comment]
The danger zone should be removed
Screenshot from 2021-05-12 02-34-29

**Comment by dreacot** [comment]
DCR should be suffixed after the balances

Screenshot from 2021-05-12 02-44-23

after the 2 digits after the decimal, the rest digits should be a lighter grey color as seen below
cbfd2298-4e84-45a7-88eb-c5e2d8f02dd3

**Comment by dreacot** [comment]
1. The number of mixers running should be displayed to user
2. Under the wallet name, what should be displayed should be the "Unmixed balance" and not the "Mixed balance"
Screenshot from 2021-05-12 02-55-24

see a reference below
6da1f305-3676-4158-af26-14b5847c4b9d (1)

**Comment by dreacot** [comment]
The "Privacy is here" card should disappear after setting up the mixer
Screenshot from 2021-05-12 03-01-25

**Comment by dreacot** [comment]
The info dialog on the mixer page isn't properly formatted
Screenshot from 2021-05-12 03-09-15

see reference below
e44e4e36-2cdb-4b9b-9295-a0ca0cbbae0c

**Comment by dreacot** [comment]
The title of some mixer settings have been changed
Screenshot from 2021-05-12 03-37-17

see reference below(also note to capitalize when necessary)
acda3fd9-0ad2-4641-9758-e9f9ded3d1cc

**Comment by dreacot** [comment]
The unmixed balance shows an exponential value when the mixer completes
Screenshot from 2021-05-12 16-29-10

**Review by C-ollins — CHANGES_REQUESTED** [review]
1. This message should be "Set up StakeShuffle here" and it should only be shown once, currently it shows whenever I open the wallets page.
  
2. This dialog returns to the overview page after refreshing, it should not return again for the current app run once dismissed. 
  
3. Overview page is still showing "Privacy is here" card after I just set up privacy.
4. Capitalise error message.

5. Capitalise "Mixer is running" and add "DCR" to the unmixed balance amount.

6. Mixed transactions should be labeled as 'Mix', modifications should be made in the transaction row and transaction details dialog title. Also, remove the double negative sign from the amount and the amount should be the mix denomination(`mix_denom` in the transaction json).

**Comment by C-ollins** [comment]
The remaining fixes will be sent as separate prs.

**Review by C-ollins — APPROVED** [review]

**Pull request merged**
